services:
  database:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: khamroev
      POSTGRES_PASSWORD: 2080
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

  backend:
    container_name: spring-boot-full-stack
    image: ghcr.io/khamroevjs/spring-boot-full-stack
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgres://database:5432/customer
    ports:
      - "8080:8080"
    networks:
      - db
    depends_on:
      - database
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: