server:
  error:
    include-message: always
    include-stacktrace: never

spring:
  devtools:
    livereload:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: khamroev
    password: 2080
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
